apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: localhost:5000/auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=AuthDB;Username=postgres;Password=postgres"
        - name: JWT__Secret
          value: "your-super-secret-key-with-minimum-32-characters"
        - name: JWT__Issuer
          value: "auth-service"
        - name: JWT__Audience
          value: "payment-service"
        - name: JWT__ExpiryInMinutes
          value: "60"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 5062
    targetPort: 8080
  type: ClusterIP 