apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: localhost:5000/cart-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=CartDB;Username=postgres;Password=postgres"
        - name: ConnectionStrings__Redis
          value: "redis:6379"
        - name: JWT__Authority
          value: "http://auth-service:5062"
        - name: JWT__Audience
          value: "cart-service"
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
  - port: 5032
    targetPort: 80
  type: ClusterIP 